### ISSUE TITLE
Unit test services -> FileSystem

### ISSUE THREAD

**Issue by JasonShin** [StormwindHQ/Stormwind#4]
Find a way to mock external libs like in Jest mock. We need to mock `import better.files.{File => ScalaFile}`, but the current approach does not look right.

We have created a class variable called `File` with an intention of overriding it in the unit test. There is a class called FakeFile located in the same file as the unit test, and it is meant to override the class variable `File`, however, it's throwing an error `not found: value FakeFile.`

Please check out the master branch's `services -> FileSystem` and `tests -> unit -> services -> FileSystemSpec`.

TODO:

- Unit test `FileSystem -> zipTaskIfNotExist`
- (Maybe) Unit test `FileSystem -> readFileAsString`

File to look at:
- https://github.com/StormwindHQ/Stormwind/blob/master/app/services/FileSystem.scala 
- https://github.com/StormwindHQ/Stormwind/blob/master/test/unit/services/FileSystemSpec.scala

Tips:
- To run unit test using `sbt`, just type `sbt test` at the project root
- To run tests only within a file `sbt "testOnly *FileSystemSpec"`; `FileSystemSpec` is name of the file

**Comment by JasonShin** [comment]
I had an interesting discussion on this topic in Scala gitter chat....

**Comment by msinton** [comment]
Can take this - I think an 'integration' test for this rather than a Unit test would protect you from upstream problems from dependencies. So would check with java.nio that it has worked as intended.

**Comment by JasonShin** [comment]
I totally agree with you, I would appreciate your contribution =)

**Comment by msinton** [comment]
While testing this I noticed that you are creating a zip within the zip (and that zip also contains a zip).
You can see this by running one of the tests with the teardown commented out.

I assume that is not intended?

**Comment by JasonShin** [comment]
I think I found the issue, as you've already mentioned, better-files zips itself over and over again when you set the target file to the directory it's trying to zip

**Comment by JasonShin** [comment]
https://github.com/pathikrit/better-files/issues/268
